/**
******************************************************************************
* @file : main.c
* @author : Auto-generated by STM32CubeIDE
* @brief : Main program body
******************************************************************************
* @attention
*
* Copyright (c) 2026 STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
******************************************************************************
*/

#include <stdint.h>
#include <stdio.h>
#include "stm32u585xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void PortH_Init(void) {

	//initialize Port H for PH6 and PH7 which are on-board user LEDs

	//enable the peripheral clock
	RCC->AHB2ENR1 |= 0x80; //set bit 7 of the register to enable the clock for port H

	GPIOH->MODER &= ~(3U << (6*2)); //Clears the two bits in PH6 (port H, pin 6)
	GPIOH->MODER |= (1 << (6*2)); //sets Pin 6 two bits to 01 to configure for output

	GPIOH->MODER &= ~(3U << (7*2)); //Clear Pin 7
	GPIOH->MODER |= (1U << (7*2)); //Pin 7: 01

}

int main(void)
{
	PortH_Init();

	while (1) {

		//USART1_WriteString("WE ARE IN THE APP\n");

		//set bits 22 and 23 (reset bits) in order to turn ON the LEDs
		GPIOH->BSRR = 0x00C00000;

		//loop for delay - make sure it doesn't get optimized by using volatile
		for (volatile int i = 0; i < 1500000; i++) {}

		//set bits 6 and 7 (set bits) in order to turn OFF the LEDs
		GPIOH->BSRR = 0x000000C0;

		for (volatile int i = 0; i < 1500000; i++) {}

	}

}
