/**
******************************************************************************
* @file : main.c
* @author : Auto-generated by STM32CubeIDE
* @brief : Main program body
******************************************************************************
* @attention
*
* Copyright (c) 2026 STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
******************************************************************************
*/

//This is the bootloader main.c file which is responsible for the handoff. Its main purpose is to emulate the way hardware allows the MCU to jump to the first instruction. The bootloader will be accessed first. It will then make use of the VTOR to jump to the application

#include <stdint.h>
#include <stdio.h>
#include "stm32u585xx.h"
#include "PLL.h"
#include "uart.h"
#include "flash.h"
#include "myMetadata.h"
#include "CRC.h"
#include "GPDMA.h"
#include "hash.h"
#include "DWT.h"

#define APP_START_ADDRESS 0x08008000 //defines the location of where the application starts (start of slot A)
#define FLASH_TEST_ADDRESS 0x08108000 //defines the location of where the bit aligned quad word will live

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef void (*jump_function)(void);
int result;
volatile uint8_t gpdma_completion_flag = 0; //when this turns 1, we read the HASH digest

const uint8_t abcd[] = {0x61,0x62,0x63,0x64,0x65};

//Interrupt Service Routine (This will be responsible for handling the DMA completion and HASH digest reading)
void GPDMA1_CH0_IRQHandler(void) {

	//first, clear the hardware flag which raised the interrupt
	if (GPDMA1_Channel0->CSR & (1U << 8)) { //TCF is raised for completion
		GPDMA1_Channel0->CFCR |= (1U << 8); //set bit 8 to clear the TCF interrupt flag
		gpdma_completion_flag = 1; //set the flag to 1
	}

	if (GPDMA1_Channel0->CSR & (1U << 10)) { //DTEF is raised for error
		GPDMA1_Channel0->CFCR |= (1U << 10); //set bit 10 to clear the data transfer ERROR flag

		while(1) {} //infinite loop in case of error

	}


}

int main(void)
{

	//PortH_Init();
	PLL_Init();
	USART1_Init();
	CRC_Init();
	DWT_Init();

	//Initialize the HASH peripheral and enable the DMA for it
	HASH_Init(5);
	


	//Start the hand-off

	result = 0;

	ICACHE->CR |= (1U << 0); //enable ICACHE

	USART1_WriteString("Going into the unlock-lock test\n");

	result = unlock_flash_nscr();
	if (result) {
		USART1_WriteString("Unlock Fail\n");
		return -1; //main() failure
	}

	// result = page_erase(&SlotMetadata);
	// if (result) {
	// 	USART1_WriteString("Erase Failed\n");
	// 	return -1; //main() failure
	// }

	//TEST REGION --------------

	// uint32_t quadWord[4] = {0,0,0,0}; //placeholder start for the quad-word to be written to memory

	// uint32_t *address = MetaData_Latest_Entry(&MD, &SlotMetadata); //this returns the address of WHERE to write the new quad_word and fills the MD struct with the latest information

    // MetaData_QuadWord(&MD, quadWord); //place the information from the Metadata struct into a quad-word

	// result = write_flash(quadWord, address); //write data to flash using an address pointer and the data to be written is stored in the quadWord being passed in
	// if (result == PGAERR) {
	// 	USART1_WriteString("PGAERR Raised\n");
	// 	return -1;
	// }
	// if (result == PROGERR) {
	// 	USART1_WriteString("PROGERR Raised\n");
	// 	return -1;
	// }
	// if (result) {
	// 	USART1_WriteString("Write Fail\n");
	// 	return -1;
	// }

	// address = MetaData_Latest_Entry(&MD, &SlotMetadata); //this returns the address of WHERE to write the new quad_word and fills the MD struct with the latest information

	// MetaData_Update_Fields(&MD, 2);

    // MetaData_QuadWord(&MD, quadWord); //place the information from the Metadata struct into a quad-word

	// result = write_flash(quadWord, address); //write data to flash using an address pointer and the data to be written is stored in the quadWord being passed in
	// if (result == PGAERR) {
	// 	USART1_WriteString("PGAERR Raised\n");
	// 	return -1;
	// }
	// if (result == PROGERR) {
	// 	USART1_WriteString("PROGERR Raised\n");
	// 	return -1;
	// }
	// if (result) {
	// 	USART1_WriteString("Write Fail\n");
	// 	return -1;
	// }

	//TEST REGION --------------

	//This function will use the GPDMA to move the 4 bytes of data from the abcd array to the address where HASH_DIN is
	uint32_t startTime = DWT->CYCCNT; //get the start time
	GPDMA_Direct_Programming((uint32_t)abcd, 5);

	//Read from HASH
	while (gpdma_completion_flag == 0) {}

	//the flag is now 1 so we proceed by extracting the hashing information
	while (HASH->SR & (1U << 3)) {} //while the BUSY bit is 1, the hash core is processing the block of data, so we wait
	while (!(HASH->SR & (1U << 1))) {} //while the DCIS bit is cleared, there is no digest available in the HASH_HRx registers
	
	uint32_t endTime = DWT->CYCCNT; //get the end time

	//Getting here means that the data has been processed and now we can work on extracting that information from the HASH registers
	char hash_string[11];
	uint32_t index;
	for (index = 0; index < 8; index++) {
		int_to_str(HASH_DIGEST->HR[index], hash_string);
		USART1_WriteString(hash_string);
		USART1_WriteString("\n");
	}

	uint32_t delta = endTime - startTime;
	char deltaPrint[20];
	int_to_str(delta, deltaPrint);
	USART1_WriteString(deltaPrint);

	lock_flash_nscr();

	const char string[] = "Going into hand-off\n";
	USART1_WriteString(string);

	__disable_irq(); //disable interrupts to ensure a proper jump

	//Read word 0 and 1 of the VTOR while remaining on the stack we are on right now
	uint32_t *app = (uint32_t*)APP_START_ADDRESS; //get access the app's start address 0x0800_8000
	uint32_t stack_pointer_value = app[0]; //read word 0
	uint32_t reset_handler_address = app[1]; //read word 1

	jump_function jump_to_app = (jump_function)reset_handler_address; //create a jump_to_app function which JUMPS to the address where the app lives and starts executing it as if it were an actual function

	//Set VTOR
	SCB->VTOR = APP_START_ADDRESS; //set the VTOR to the start of the app's address

	const char string2[] = "Jumping Now\n";
	USART1_WriteString(string2);

	//Set the Stack Pointer to the app's word 0 value
	__set_MSP(stack_pointer_value);

	//Branch to application
	jump_to_app();

	while (1) {

	}

}
