/**
******************************************************************************
* @file : main.c
* @author : Auto-generated by STM32CubeIDE
* @brief : Main program body
******************************************************************************
* @attention
*
* Copyright (c) 2026 STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
******************************************************************************
*/

//This is the bootloader main.c file which is responsible for the handoff. Its main purpose is to emulate the way hardware allows the MCU to jump to the first instruction. The bootloader will be accessed first. It will then make use of the VTOR to jump to the application

#include <stdint.h>
#include <stdio.h>
#include "stm32u585xx.h"
#include "PLL.h"
#include "uart.h"
#include "flash.h"
#include "myMetadata.h"
#include "CRC.h"

#define APP_START_ADDRESS 0x08008000 //defines the location of where the application starts (start of slot A)
#define FLASH_TEST_ADDRESS 0x08108000 //defines the location of where the bit aligned quad word will live

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef void (*jump_function)(void);

int main(void)
{
	//PortH_Init();
	PLL_Init();
	USART1_Init();
	CRC_Init();

	//Start the hand-off

	ICACHE->CR |= (1U << 0); //enable ICACHE

	USART1_WriteString("Going into the unlock-lock test\n");

	unlock_flash_nscr();

	page_erase(&SlotMetadata);

	//TEST REGION

	uint32_t quadWord[4] = {0,0,0,0}; //placeholder start for the quad-word to be written to memory

	uint32_t *address = MetaData_Latest_Entry(&MD, &SlotMetadata); //this returns the address of WHERE to write the new quad_word and fills the MD struct with the latest information

    MetaData_QuadWord(&MD, quadWord); //place the information from the Metadata struct into a quad-word

	write_flash(quadWord, address); //write data to flash using an address pointer and the data to be written is stored in the quadWord being passed in

	address = MetaData_Latest_Entry(&MD, &SlotMetadata); //this returns the address of WHERE to write the new quad_word and fills the MD struct with the latest information

	MetaData_Update_Fields(&MD, 2);

    MetaData_QuadWord(&MD, quadWord); //place the information from the Metadata struct into a quad-word

	write_flash(quadWord, address); //write data to flash using an address pointer and the data to be written is stored in the quadWord being passed in

	//TEST REGION

	lock_flash_nscr();

	const char string[] = "Going into hand-off\n";
	USART1_WriteString(string);

	__disable_irq(); //disable interrupts to ensure a proper jump

	//Read word 0 and 1 of the VTOR while remaining on the stack we are on right now
	uint32_t *app = (uint32_t*)APP_START_ADDRESS; //get access the app's start address 0x0800_8000
	uint32_t stack_pointer_value = app[0]; //read word 0
	uint32_t reset_handler_address = app[1]; //read word 1

	jump_function jump_to_app = (jump_function)reset_handler_address; //create a jump_to_app function which JUMPS to the address where the app lives and starts executing it as if it were an actual function

	//Set VTOR
	SCB->VTOR = APP_START_ADDRESS; //set the VTOR to the start of the app's address

	const char string2[] = "Jumping Now\n";
	USART1_WriteString(string2);

	//Set the Stack Pointer to the app's word 0 value
	__set_MSP(stack_pointer_value);

	//Branch to application
	jump_to_app();

	while (1) {

	}

}
